use anyhow::Result;
use std::path::Path;

use crate::config::ProjectConfig;
use crate::features::FeatureSpec;

pub struct DockerGenerator<'a> {
    config: &'a ProjectConfig,
    features: &'a [FeatureSpec],
}

impl<'a> DockerGenerator<'a> {
    pub fn new(config: &'a ProjectConfig, features: &'a [FeatureSpec]) -> Self {
        Self { config, features }
    }

    pub fn generate(&self, out: &Path) -> Result<()> {
        std::fs::write(out.join("Dockerfile"), self.render_dockerfile())?;
        std::fs::write(out.join("docker-compose.yml"), self.render_compose())?;
        std::fs::write(
            out.join("docker-compose.override.yml"),
            self.render_compose_override(),
        )?;
        std::fs::write(out.join(".dockerignore"), self.render_dockerignore())?;
        Ok(())
    }

    fn render_dockerfile(&self) -> String {
        let d = &self.config.docker;
        let artifact = crate::engine::to_artifact_id(&self.config.project.name);
        let version = &self.config.project.version;

        format!(
            r#"# ─────────────────────────────────────────────────────────
# Multi-stage Dockerfile — generated by SpringGen
# ─────────────────────────────────────────────────────────

# ── Stage 1: Build ────────────────────────────────────────
FROM eclipse-temurin:{java_version}-jdk-alpine AS builder
WORKDIR /workspace

# Cache dependencies layer
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline -B -q

# Build application
COPY src ./src
RUN ./mvnw package -DskipTests -B -q

# Extract layers for optimal caching
RUN java -Djarmode=layertools \
    -jar target/{artifact}-{version}.jar extract \
    --destination target/extracted

# ── Stage 2: Runtime ─────────────────────────────────────
FROM {base_image}
WORKDIR /app

# Security: run as non-root
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# JVM tuning environment variables
ENV JAVA_OPTS="-XX:+UseContainerSupport \
               -XX:MaxRAMPercentage=75.0 \
               -XX:+OptimizeStringConcat \
               -Djava.security.egd=file:/dev/./urandom"

# Copy extracted layers (optimal cache invalidation)
COPY --from=builder /workspace/target/extracted/dependencies/ ./
COPY --from=builder /workspace/target/extracted/spring-boot-loader/ ./
COPY --from=builder /workspace/target/extracted/snapshot-dependencies/ ./
COPY --from=builder /workspace/target/extracted/application/ ./

EXPOSE {port}

HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
    CMD wget -qO- http://localhost:{port}/actuator/health || exit 1

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS org.springframework.boot.loader.launch.JarLauncher"]
"#,
            java_version = self.config.project.java_version,
            artifact = artifact,
            version = version,
            base_image = d.base_image,
            port = d.app_port,
        )
    }

    fn render_compose(&self) -> String {
        let artifact = crate::engine::to_artifact_id(&self.config.project.name);
        let port = self.config.docker.app_port;

        let mut services = String::new();
        let mut volumes: Vec<String> = Vec::new();

        // ── Infrastructure services ──────────────────────────────────────────
        for feature in self.features {
            for svc in feature.docker_services {
                services.push_str(&self.render_service(svc));
                for vol in svc.volumes {
                    // Extract the named volume part (before the colon)
                    if let Some(vol_name) = vol.split(':').next() {
                        if !vol_name.starts_with('.') && !vol_name.starts_with('/') {
                            if !volumes.contains(&vol_name.to_string()) {
                                volumes.push(vol_name.to_string());
                            }
                        }
                    }
                }
            }
        }

        // ── Application service ──────────────────────────────────────────────
        let infra_services: Vec<&str> = self
            .features
            .iter()
            .flat_map(|f| f.docker_services.iter().map(|s| s.name))
            .collect();

        let depends = if infra_services.is_empty() {
            String::new()
        } else {
            let deps_yaml = infra_services
                .iter()
                .map(|svc| format!("      {svc}:\n        condition: service_healthy"))
                .collect::<Vec<_>>()
                .join("\n");
            format!("    depends_on:\n{}\n", deps_yaml)
        };

        let env_keys: Vec<String> = self
            .features
            .iter()
            .flat_map(|f| {
                f.env_vars
                    .iter()
                    .map(|(k, _)| format!("      {k}: ${{{k}}}"))
            })
            .collect();
        let env_section = if env_keys.is_empty() {
            String::new()
        } else {
            format!("    environment:\n{}\n", env_keys.join("\n"))
        };

        services.push_str(&format!(
            r#"  # ─────────────────────────────────────────────────────────
  # Application
  # ─────────────────────────────────────────────────────────
  {artifact}:
    build:
      context: .
      dockerfile: Dockerfile
    image: {artifact}:latest
    container_name: {artifact}
    ports:
      - "${{SERVER_PORT:{port}}}:{port}"
{env_section}{depends}    restart: unless-stopped
    networks:
      - app-network

"#,
            artifact = artifact,
            port = port,
            env_section = env_section,
            depends = depends,
        ));

        let volumes_section = if volumes.is_empty() {
            String::new()
        } else {
            let vol_list = volumes
                .iter()
                .map(|v| format!("  {}:", v))
                .collect::<Vec<_>>()
                .join("\n");
            format!("\nvolumes:\n{}\n", vol_list)
        };

        format!(
            r#"# ─────────────────────────────────────────────────────────
# Docker Compose — generated by SpringGen
# Run: docker-compose up -d
# ─────────────────────────────────────────────────────────
name: {artifact}

services:
{services}
networks:
  app-network:
    driver: bridge
{volumes_section}"#,
            artifact = artifact,
            services = services,
            volumes_section = volumes_section,
        )
    }

    fn render_compose_override(&self) -> String {
        let artifact = crate::engine::to_artifact_id(&self.config.project.name);
        format!(
            r#"# ─────────────────────────────────────────────────────────
# docker-compose.override.yml — local dev overrides
# This file is auto-applied by docker-compose for local dev.
# Do NOT commit environment secrets here.
# ─────────────────────────────────────────────────────────
name: {artifact}

services:
  {artifact}:
    env_file:
      - .env
    volumes:
      - ./src:/workspace/src:ro   # hot reload with devtools
"#,
            artifact = artifact
        )
    }

    fn render_service(&self, svc: &crate::features::DockerService) -> String {
        let mut s = format!(
            "  # ─────────────────────────────────────────────────────────\n  # {name}\n  # ─────────────────────────────────────────────────────────\n  {name}:\n    image: {image}\n",
            name = svc.name,
            image = svc.image,
        );

        s.push_str("    container_name: ");
        s.push_str(svc.name);
        s.push('\n');

        if !svc.ports.is_empty() {
            s.push_str("    ports:\n");
            for p in svc.ports {
                s.push_str(&format!("      - \"{}\"\n", p));
            }
        }

        if !svc.environment.is_empty() {
            s.push_str("    environment:\n");
            for (k, v) in svc.environment {
                s.push_str(&format!("      {k}: {v}\n"));
            }
        }

        if !svc.volumes.is_empty() {
            s.push_str("    volumes:\n");
            for v in svc.volumes {
                s.push_str(&format!("      - {v}\n"));
            }
        }

        if let Some(hc) = svc.healthcheck {
            s.push_str(&format!(
                "    healthcheck:\n      test: [\"CMD-SHELL\", \"{}\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n      start_period: 30s\n",
                hc
            ));
        }

        if !svc.depends_on.is_empty() {
            s.push_str("    depends_on:\n");
            for dep in svc.depends_on {
                s.push_str(&format!(
                    "      {dep}:\n        condition: service_healthy\n"
                ));
            }
        }

        s.push_str("    restart: unless-stopped\n");
        s.push_str("    networks:\n      - app-network\n\n");

        s
    }

    fn render_dockerignore(&self) -> String {
        r#"# Maven build output
target/

# IDE
.idea/
*.iml
.eclipse/
*.class

# Dev files
**/*.md
.git/
.gitignore

# Environment
.env
!.env.example

# Docker
docker-compose.override.yml
"#
        .to_string()
    }
}
