use anyhow::Result;
use indexmap::IndexMap;
use std::path::Path;

use crate::config::ProjectConfig;
use crate::features::FeatureSpec;

pub struct EnvFileGenerator<'a> {
    config: &'a ProjectConfig,
    features: &'a [FeatureSpec],
}

impl<'a> EnvFileGenerator<'a> {
    pub fn new(config: &'a ProjectConfig, features: &'a [FeatureSpec]) -> Self {
        Self { config, features }
    }

    pub fn generate(&self, out: &Path) -> Result<()> {
        let env_example = self.render();
        // .env.example is committed; .env is gitignored
        std::fs::write(out.join(".env.example"), &env_example)?;
        // Write .env with the same content as a starting point (excluded from git)
        if !out.join(".env").exists() {
            std::fs::write(out.join(".env"), &env_example)?;
        }
        Ok(())
    }

    fn render(&self) -> String {
        let mut vars: IndexMap<String, String> = IndexMap::new();

        // Always-present
        vars.insert("SPRING_PROFILES_ACTIVE".to_string(), "dev".to_string());
        vars.insert("SERVER_PORT".to_string(), "8080".to_string());

        // Collect feature-driven vars (deduped)
        for feature in self.features {
            for (key, val) in feature.env_vars {
                vars.entry(key.to_string()).or_insert(val.to_string());
            }
        }

        let mut out = String::new();
        out.push_str("# ─────────────────────────────────────────────────────────\n");
        out.push_str(&format!(
            "# {} — generated by SpringGen\n",
            self.config.project.name
        ));
        out.push_str("# Copy this file to .env and fill in real values.\n");
        out.push_str("# NEVER commit .env to source control.\n");
        out.push_str("# ─────────────────────────────────────────────────────────\n\n");

        // Group vars by category
        let sections: &[(&str, &[&str])] = &[
            ("Application", &["SPRING_PROFILES_ACTIVE", "SERVER_PORT"]),
            (
                "Database",
                &[
                    "DB_HOST",
                    "DB_PORT",
                    "DB_NAME",
                    "DB_USER",
                    "DB_PASSWORD",
                    "DB_POOL_MAX",
                ],
            ),
            (
                "Redis",
                &[
                    "REDIS_HOST",
                    "REDIS_PORT",
                    "REDIS_PASSWORD",
                    "REDIS_DB",
                    "REDIS_SENTINEL_MASTER",
                    "REDIS_SENTINEL_NODES",
                    "REDIS_SENTINEL_PASSWORD",
                    "REDIS_SSL_KEYSTORE",
                    "REDIS_SSL_KEYSTORE_PASSWORD",
                    "REDIS_SSL_TRUSTSTORE",
                    "REDIS_SSL_TRUSTSTORE_PASSWORD",
                ],
            ),
            (
                "Kafka",
                &["KAFKA_BOOTSTRAP_SERVERS", "KAFKA_LISTENER_CONCURRENCY"],
            ),
            (
                "MongoDB",
                &[
                    "MONGO_HOST",
                    "MONGO_PORT",
                    "MONGO_DB",
                    "MONGO_USER",
                    "MONGO_PASSWORD",
                ],
            ),
            (
                "Security",
                &[
                    "JWT_SECRET",
                    "JWT_ACCESS_EXPIRY_MS",
                    "JWT_REFRESH_EXPIRY_MS",
                    "SECURITY_USER",
                    "SECURITY_PASSWORD",
                    "OAUTH2_ISSUER_URI",
                    "OAUTH2_JWK_URI",
                ],
            ),
            (
                "S3",
                &[
                    "S3_BUCKET",
                    "AWS_REGION",
                    "S3_ENDPOINT",
                    "S3_PATH_STYLE",
                    "AWS_ACCESS_KEY_ID",
                    "AWS_SECRET_ACCESS_KEY",
                ],
            ),
            (
                "Mail",
                &[
                    "MAIL_HOST",
                    "MAIL_PORT",
                    "MAIL_USER",
                    "MAIL_PASSWORD",
                    "MAIL_FROM",
                ],
            ),
            ("Tracing", &["ZIPKIN_ENDPOINT", "TRACING_SAMPLE_RATE"]),
            (
                "Elasticsearch",
                &[
                    "ELASTICSEARCH_URIS",
                    "ELASTICSEARCH_USER",
                    "ELASTICSEARCH_PASSWORD",
                ],
            ),
            ("WebSocket", &["WS_ALLOWED_ORIGINS"]),
        ];

        let mut written: Vec<String> = Vec::new();

        for (section, keys) in sections {
            let section_vars: Vec<_> = keys.iter().filter(|k| vars.contains_key(**k)).collect();

            if !section_vars.is_empty() {
                out.push_str(&format!(
                    "# ── {} ────────────────────────────────────────────────\n",
                    section
                ));
                for key in section_vars {
                    let val = &vars[*key];
                    out.push_str(&format!("{}={}\n", key, val));
                    written.push(key.to_string());
                }
                out.push('\n');
            }
        }

        // Any remaining vars not in known sections
        let remaining: Vec<_> = vars.keys().filter(|k| !written.contains(k)).collect();
        if !remaining.is_empty() {
            out.push_str("# ── Other ───────────────────────────────────────────────\n");
            for key in remaining {
                out.push_str(&format!("{}={}\n", key, vars[key]));
            }
        }

        out
    }
}
