use anyhow::Result;
use std::path::Path;

use crate::config::ProjectConfig;
use crate::features::FeatureSpec;

pub struct PropertiesGenerator<'a> {
    config: &'a ProjectConfig,
    features: &'a [FeatureSpec],
}

impl<'a> PropertiesGenerator<'a> {
    pub fn new(config: &'a ProjectConfig, features: &'a [FeatureSpec]) -> Self {
        Self { config, features }
    }

    pub fn generate(&self, out: &Path) -> Result<()> {
        let resources = out.join("src/main/resources");
        std::fs::create_dir_all(&resources)?;

        std::fs::write(resources.join("application.yml"), self.render_base())?;
        std::fs::write(resources.join("application-dev.yml"), self.render_dev())?;
        std::fs::write(resources.join("application-prod.yml"), self.render_prod())?;
        Ok(())
    }

    fn render_base(&self) -> String {
        let meta = &self.config.project;
        let artifact = crate::engine::to_artifact_id(&meta.name);

        let mut yaml = format!(
            r#"# ─────────────────────────────────────────────────────────
# Application — generated by SpringGen
# ─────────────────────────────────────────────────────────
spring:
  application:
    name: {artifact}
  profiles:
    active: ${{SPRING_PROFILES_ACTIVE:dev}}

  # Jackson defaults
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: ${{SERVER_PORT:8080}}
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
  error:
    include-message: always
    include-binding-errors: always

"#,
            artifact = artifact
        );

        // ── Feature-driven properties ────────────────────────────────────────
        if self.has("redis") || self.has("redis-ssl") || self.has("redis-sentinel") {
            yaml.push_str(&self.redis_yaml());
        }

        if self.has("kafka") {
            yaml.push_str(&self.kafka_yaml());
        }

        if self.has("postgres") {
            yaml.push_str(&self.postgres_yaml());
        }

        if self.has("mysql") {
            yaml.push_str(&self.mysql_yaml());
        }

        if self.has("mongodb") {
            yaml.push_str(&self.mongodb_yaml());
        }

        if self.has("elasticsearch") {
            yaml.push_str(&self.elasticsearch_yaml());
        }

        if self.has("security") || self.has("jwt") || self.has("oauth2") {
            yaml.push_str(&self.security_yaml());
        }

        if self.has("openapi") {
            yaml.push_str(&self.openapi_yaml());
        }

        if self.has("actuator") {
            yaml.push_str(&self.actuator_yaml());
        }

        if self.has("tracing") {
            yaml.push_str(&self.tracing_yaml());
        }

        if self.has("email") {
            yaml.push_str(&self.email_yaml());
        }

        if self.has("s3") {
            yaml.push_str(&self.s3_yaml());
        }

        if self.has("websocket") {
            yaml.push_str(&self.websocket_yaml());
        }

        // Extra properties from config
        for (k, v) in &self.config.extra_properties {
            yaml.push_str(&format!("{}: {}\n", k, v));
        }

        yaml.push_str(
            "\n# Application-specific configuration\napp:\n  name: ${spring.application.name}\n",
        );

        yaml
    }

    fn render_dev(&self) -> String {
        let mut yaml = r#"# ─────────────────────────────────────────────────────────
# Development profile overrides
# ─────────────────────────────────────────────────────────
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

"#
        .to_string();

        if self.has("openapi") {
            yaml.push_str(
                "springdoc:\n  swagger-ui:\n    enabled: true\n  api-docs:\n    enabled: true\n\n",
            );
        }

        yaml
    }

    fn render_prod(&self) -> String {
        r#"# ─────────────────────────────────────────────────────────
# Production profile overrides
# ─────────────────────────────────────────────────────────
logging:
  level:
    root: WARN
    com.example: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
"#
        .to_string()
    }

    // ── Section renderers ─────────────────────────────────────────────────────

    fn redis_yaml(&self) -> String {
        let r = &self.config.redis;
        match r.mode.as_str() {
            "ssl" => format!(
                r#"  # ── Redis (SSL/TLS) ────────────────────────────────────
  data:
    redis:
      host: ${{REDIS_HOST:{}}}
      port: ${{REDIS_PORT:{}}}
      password: ${{REDIS_PASSWORD:}}
      ssl:
        enabled: true
        bundle: redis-ssl
      lettuce:
        pool:
          max-active: {}
          max-idle: {}
          min-idle: {}
  ssl:
    bundle:
      jks:
        redis-ssl:
          keystore:
            location: ${{REDIS_SSL_KEYSTORE:classpath:ssl/redis-client.p12}}
            password: ${{REDIS_SSL_KEYSTORE_PASSWORD:changeit}}
          truststore:
            location: ${{REDIS_SSL_TRUSTSTORE:classpath:ssl/redis-truststore.p12}}
            password: ${{REDIS_SSL_TRUSTSTORE_PASSWORD:changeit}}

"#,
                r.host, r.port, r.pool_max_active, r.pool_max_idle, r.pool_min_idle
            ),

            "sentinel" => {
                let nodes = r.sentinel.nodes.join(",");
                format!(
                    r#"  # ── Redis (Sentinel HA) ─────────────────────────────────
  data:
    redis:
      sentinel:
        master: ${{REDIS_SENTINEL_MASTER:{}}}
        nodes: ${{REDIS_SENTINEL_NODES:{}}}
        password: ${{REDIS_SENTINEL_PASSWORD:}}
      password: ${{REDIS_PASSWORD:}}
      database: ${{REDIS_DB:0}}
      lettuce:
        pool:
          max-active: {}
          max-idle: {}
          min-idle: {}
          max-wait: -1ms

"#,
                    r.sentinel.master, nodes, r.pool_max_active, r.pool_max_idle, r.pool_min_idle
                )
            }

            _ => format!(
                r#"  # ── Redis (Standalone) ──────────────────────────────────
  data:
    redis:
      host: ${{REDIS_HOST:{}}}
      port: ${{REDIS_PORT:{}}}
      password: ${{REDIS_PASSWORD:}}
      database: ${{REDIS_DB:0}}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: {}
          max-idle: {}
          min-idle: {}

"#,
                r.host, r.port, r.pool_max_active, r.pool_max_idle, r.pool_min_idle
            ),
        }
    }

    fn kafka_yaml(&self) -> String {
        let k = &self.config.kafka;
        format!(
            r#"  # ── Kafka ────────────────────────────────────────────────
  kafka:
    bootstrap-servers: ${{KAFKA_BOOTSTRAP_SERVERS:{}}}
    consumer:
      group-id: ${{KAFKA_GROUP_ID:{}}}
      auto-offset-reset: {}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      properties:
        enable.idempotence: true
    listener:
      concurrency: ${{KAFKA_LISTENER_CONCURRENCY:{}}}
      ack-mode: BATCH

"#,
            k.bootstrap_servers, k.consumer_group_id, k.auto_offset_reset, k.listener_concurrency
        )
    }

    fn postgres_yaml(&self) -> String {
        let d = &self.config.database;
        format!(
            r#"  # ── PostgreSQL ───────────────────────────────────────────
  datasource:
    url: jdbc:postgresql://${{DB_HOST:{}}}:${{DB_PORT:{}}}/${{DB_NAME:{}}}?sslmode=prefer
    username: ${{DB_USER:{}}}
    password: ${{DB_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${{DB_POOL_MAX:{}}}
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        default_schema: public
    open-in-view: false
  flyway:
    enabled: {}
    locations: classpath:db/migration
    baseline-on-migrate: true

"#,
            d.host, d.port, d.name, d.username, d.pool_max_size, d.flyway_enabled
        )
    }

    fn mysql_yaml(&self) -> String {
        let d = &self.config.database;
        format!(
            r#"  # ── MySQL ────────────────────────────────────────────────
  datasource:
    url: jdbc:mysql://${{DB_HOST:{}}}:${{DB_PORT:3306}}/${{DB_NAME:{}}}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${{DB_USER:{}}}
    password: ${{DB_PASSWORD:}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${{DB_POOL_MAX:{}}}
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: true

"#,
            d.host, d.name, d.username, d.pool_max_size
        )
    }

    fn mongodb_yaml(&self) -> String {
        r#"  # ── MongoDB ──────────────────────────────────────────────
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:appdb}
      auto-index-creation: true

"#
        .to_string()
    }

    fn elasticsearch_yaml(&self) -> String {
        r#"  # ── Elasticsearch ────────────────────────────────────────
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USER:elastic}
    password: ${ELASTICSEARCH_PASSWORD:elastic}
    socket-timeout: 10s
    connection-timeout: 3s

"#
        .to_string()
    }

    fn security_yaml(&self) -> String {
        let mut s = String::from("  # ── Security ──────────────────────────────────────────\n");

        if self.has("jwt") {
            let sec = &self.config.security;
            s.push_str(&format!(
                r#"
# JWT configuration (app-level, not Spring namespace)
app:
  jwt:
    secret: ${{JWT_SECRET:change-me-in-production-with-a-256bit-key}}
    access-token-expiry-ms: ${{JWT_ACCESS_EXPIRY_MS:{}}}
    refresh-token-expiry-ms: ${{JWT_REFRESH_EXPIRY_MS:{}}}

"#,
                sec.access_token_expiry_ms, sec.refresh_token_expiry_ms
            ));
        }

        if self.has("oauth2") {
            let uri = self
                .config
                .security
                .oauth2_issuer_uri
                .as_deref()
                .unwrap_or("http://localhost:8180/realms/app");
            s.push_str(&format!(
                r#"  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${{OAUTH2_ISSUER_URI:{}}}

"#,
                uri
            ));
        }

        s
    }

    fn openapi_yaml(&self) -> String {
        let name = &self.config.project.name;
        format!(
            r#"# ── OpenAPI ──────────────────────────────────────────────
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
  info:
    title: {} API
    version: v1
    description: "API documentation for {}"

"#,
            name, name
        )
    }

    fn actuator_yaml(&self) -> String {
        r#"# ── Actuator ─────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  info:
    env:
      enabled: true
    git:
      enabled: true

"#
        .to_string()
    }

    fn tracing_yaml(&self) -> String {
        r#"# ── Distributed Tracing ──────────────────────────────────
management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_RATE:1.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

"#
        .to_string()
    }

    fn email_yaml(&self) -> String {
        r#"# ── Mail ─────────────────────────────────────────────────
spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  mail:
    from: ${MAIL_FROM:noreply@example.com}

"#
        .to_string()
    }

    fn s3_yaml(&self) -> String {
        r#"# ── AWS S3 / MinIO ───────────────────────────────────────
app:
  s3:
    bucket: ${S3_BUCKET:app-uploads}
    region: ${AWS_REGION:us-east-1}
    endpoint: ${S3_ENDPOINT:}
    path-style-access: ${S3_PATH_STYLE:false}

"#
        .to_string()
    }

    fn websocket_yaml(&self) -> String {
        r#"# ── WebSocket ────────────────────────────────────────────
app:
  websocket:
    allowed-origins: ${WS_ALLOWED_ORIGINS:*}
    endpoint: /ws
    topic-prefix: /topic
    app-prefix: /app

"#
        .to_string()
    }

    fn has(&self, key: &str) -> bool {
        self.features.iter().any(|f| f.key == key)
    }
}
